### ISSUE TITLE
Ombi Yaml Config Correction

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#1]
The yaml for Ombi is incorrect on the volume line. It is cross linked to Organizr.

**Comment by shadowsbane0** [comment]
Not familiar enough with pull request. I was going to post this again there when I saw the “know how to fix an issue”

**Comment by shadowsbane0** [comment]
The yaml file for Ombi has an error in the volume line. It is cross linked to Organizr currently reads ${ORGANIZRNAME} as opposed to ${OMBINAME}.

**Comment by TechPerplexed** [comment]
Thanks @shadowsbane0 ! Also for taking your issues to the correct project now, that'll make life easier for us 😆 

I would imagine this is a super easy issue for @kelinger to correct, so stay tuned... you're our first "official customer" and this is our first "official ticket", so stay tuned 👍

**Comment by kelinger** [comment]
This has been corrected and can be updated with an "omni update" command or "git pull" within the omni home.

**Comment by shadowsbane0** [comment]
Seriously first? That’s funny. I guess its because I’m retired and play around with this in between homesteading the rural life. I’m a life learner and I guess I do it because I can now do it for fun and not because its my job - I’m a systems integration burnout in my former life. I’m happy to test anything you want to play with. I’m trying this out while learning the nuances of btrfs as my underlying file system and running this on Debian 11. BTW the changes in the mergerfs scripting fixed the version problem I was having with Gooby. I was having to mark hold the version @2.28 for it to come up. I still had it on hold when I changed to Omni a recently released it to see what it would do and didn’t have any issues with the mounts getting recreated.

**Comment by TechPerplexed** [comment]
Yep, you're the first! We snuck in that branch without any fanfare because although Omni works (we have both been dogfooding our own project for a few months now), it's not exactly ready yet for prime time. So now that you took the plunge, you may still be a victim of rapid development issues from time to time.

I'll close this issue now since it seems it's been resolved :)
