### ISSUE TITLE
Slow networking inside containers.

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#10]
Any idea why the docker container networking is slow. IE. Running Speedtest from CLI on host I’m getting 900+ Mbps. Using the Speedtest container I’m getting less than 100 Mbps.

**Comment by kelinger** [comment]
The speedtest CLI checks between your server and a nearby host on the Internet while the speedtest container tests the speed between your browser and the server.

So, for example, my server is in Paris and I am in the United States.  The CLI is going to test my Internet speed (ie, verify that the ISP is truly delivering what I'm paying for) while the speedtest container is meant to test the user experience (in my case, streaming a large amount of data from Paris to the US).

But, this may not be your situation nor may it be the question you intended to ask so let me know if that answers it or just makes things worse 😄
