### ISSUE TITLE
Omnimount bouncing

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#11]
Hello again! 

Finally finished pulling all of my data down. Quick off topic: NetData issue resolved itself some time back I just didn’t get a chance to mention it. Can’t say if it was a system update or something you did.

Back on topic. Omnimount is bouncing for some reason. It will get to startup complete and then issue a shutdown command. 

My setup is now simplified. I have all of my content local on a raid’d enclosure. The enclosure is a mount point called “Media” in my user home directory. I ran the rclone setup again and created a new local remote. I chose it as my media directory and exited leaving it to default to /Media. 

This isn’t ideal for me but after creating a local remote and choosing it. OmniStream assumes the user home directory as default. I gathered this after multiple attempts of mounting locations. Omni Menu setups defaults the the user home if you select to chose a media folder other than /Media (which I have anyway now in the user home). You are only allowed to select from a single directory in whatever your rclone remote directory happens to be. There is no option to select a subdirectory from any of the directories listed. Example. I had my mountpoint mounted at ~/OmniStream/mnt/mount but creating a local rclone remote forced me to ~/ and if I selected OmniStream to get to the ~/OmniStream/mnt/mount directory my Media mountpoint would be set as ~/OmniStream.

The main reason it isn’t ideal is because when Omni Backup script kicks off it tries to backup my Media mountpoint because it isn’t included in the ~/OmniStream/mnt exclusion. I’m not sure how long it would take to try and backup and compress 52TB of content but I decided to kill the process - not to mention my host system doesn’t have the space to hold that file anyway.

Omnimount is correctly creating the rclone remote, cloud, unsynched, and uploadcache folders but is removing them when it bounces. There is a mention of a “fusermount extra argument after mount point” error in the logs.

Here is log output:

>Starting vnstat

> Configuration:

MERGEMOUNT=cloud
RCLONESERVICE=Junker
RCLONEMOUNT=Junker
UNSYNCED=unsynced
UPLOADCACHE=uploadcache
MEDIA=Media
TURBOMAX=20
addgroup: The group `omniuser' already exists.
adduser: The user `omniuser' already exists.
Starting services
{
        "jobid": 1
}

Startup complpete
Received request to shutdown
fusermount: extra arguments after the mountpoint
rmdir: failed to remove '/mnt/uploadcache': Directory not empty
rclone v1.58.0
- os/version: debian 11.3 (64 bit)
- os/kernel: 5.10.0-13-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.8
- go/linking: static
- go/tags: none

mergerfs version: 2.33.5

**Comment by TechPerplexed** [comment]
Welcome back @shadowsbane0 😄 So, I'm probably completely misunderstanding what you are asking, but if I read you correctly, you are wanting to use the mounts for local storage, not so much Google/Dropbox/etc right?

So one idea could be to use the "unsynced" mount for that purpose. For example I have a test server at home with two hard drives - one small SSD and a large HDD drive with a number of movies/TV shows. I have simply mounted the HDD to ..../mnt/unsynced and that is what the test server uses for its content - not the stuff I have in Google. In fact it doesn't touch Google at all.

Again, I might misunderstand what you're saying, if so, please eloborate 😆

**Comment by shadowsbane0** [comment]
No Ken, you understood correctly. I was trying to figure the easiest way to get a local mount available within the Omni environment the containers would have access to my content.

I thought I would be able to do it easiest by just creating a rclone “local remote” (currently option 24) but ran into the complications mentioned with omnimount.



Sent from my iPhone

On Apr 27, 2022, at 9:00 PM, Tech Perplexed ***@***.***> wrote:

﻿

Welcome back @shadowsbane0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshadowsbane0&data=05%7C01%7C%7Ca52893fcf86145f2f34008da28b26c16%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637867044027479573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CYjj4aRXY9pkHGAHHvaHFm2sTZAkpAGwsgFoTPrTnZQ%3D&reserved=0> 😄 So, I'm probably completely misunderstanding what you are asking, but if I read you correctly, you are wanting to use the mounts for local storage, not so much Google/Dropbox/etc right?

So one idea could be to use the "unsynced" mount for that purpose. For example I have a test server at home with two hard drives - one small SSD and a large HDD drive with a number of movies/TV shows. I have simply mounted the HDD to ..../mnt/unsynced and that is what the test server uses for its content - not the stuff I have in Google. In fact it doesn't touch Google at all.

Again, I might misunderstand what you're saying, if so, please eloborate 😆

**Comment by shadowsbane0** [comment]
@kelinger @TechPerplexed 

I don’t think the issue is with the rclone “local remote”. I deleted my  config and started created a new remote pointing to my GDrive. I’m still getting the “Fusermount: extra arguments after mountpoint” error and omnimount is in a boot loop.

**Comment by shadowsbane0** [comment]
@kelinger @TechPerplexed 

Boot loop fixed for GDrive config. I reinstalled rclone and ran setup-again script to recreate my rclone.conf. It now works with the GDrive settings. I tried to create a second “local” remote and selected it as my media location - Omnimount bootloops. It also bootloops if it is just the local remote option only - both with the Fusermount error mentioned previously. (Local remote is now storage option 19 in the rclone config). Gooby used to create a “local” remote on its own. I never saw what it was used for since I was only using GDrive at the time. 

Can you expound on how you are setting up to use the unsynced directory? It seems to be created and deleted when omnimount is up and down. If I can easily go down that path it will likely save me some time.

**Comment by shadowsbane0** [comment]
@kelinger @TechPerplexed 

I went ahead and “solved” the problem by moving my mount points into the OmniStream /mnt directory (so they would be excluded from the backup cron) and manually added it to my .yaml volumes after moving them into the 800 block. Unless you feel like tracking down why the rclone “local remote” causes boot looping of omnimount you can close this one.

**Comment by kelinger** [comment]
That's just it... it HAS to be in the OmniStream/mnt if it is managed by OmniStream.  When you pass the variables into the containers, the paths (used by OmniStream which is managed outside of Docker) are local to the machine, not the Docker containers.  Thus, I have to strip the path from the directory when it is referenced inside Docker.  In other words, you may path /this/is/where/I/store/my/media as the full path to $MEDIA but OmniMount strips off all but /media and adds /mnt to it so that it sees (and accesses) it in it's own root /mnt/media.
