### ISSUE TITLE
Radarr DOA

### ISSUE THREAD

**Issue by bdschuster** [kelinger/OmniStream#15]
Linking this to Gooby issue as well, but experiencing the same thing on Omni. https://github.com/TechPerplexed/Gooby/issues/209#issue-1302482512
Chatted on discord, they are thinking its a variable in the YAML the new version doesn't like, but one that's not even causing it to see the config. It is not the health check as I disabled and still had the issue.
If I run with blank config and newest version, it's fine: 
`docker run -d --rm --name=radarr --tmpfs /config -p 7878:7878 lscr.io/linuxserver/radarr:latest`
But running in the Omni yaml with latest, fails to start.
Dropping back to 4.1.0.6175-ls145 works fine, starts up no issues.
https://github.com/TechPerplexed/Gooby/issues/209#issue-1302482512

**Comment by kelinger** [comment]
For me, Radarr (latest) doesn't work even with a blank config.  Clearly a problem on Radarr's side.  I'll keep an eye out for an update from them but yes, in the meantime, you may want/need to force it to a specific version that works.

**Comment by TechPerplexed** [comment]
@bdschuster try to update your Omni - @kelinger just pushed an update. I also asked the Gooby user to comment out one line to see if it solves their issue :)

**Comment by bdschuster** [comment]
@TechPerplexed I'm having a long day moment..lol...how do I fix this again?
`Updating a222658..a4737f8
error: Your local changes to the following files would be overwritten by merge:
        components/301-radarr.yaml
        healthchecks/radarrcheck
Please commit your changes or stash them before you merge.
Aborting`

**Comment by kelinger** [comment]
This is because you modified those files.  Just delete them entirely and the next "omni update" will redownload them.

**Comment by bdschuster** [comment]
Working now! Thank you!
