### ISSUE TITLE
404 on all websites

### ISSUE THREAD

**Issue by wickedshrapnel** [kelinger/OmniStream#23]
New setup, everything was working til I ran out of local space. rclone container stopped and lost access to remote disk. Got that working https://github.com/kelinger/OmniStream/issues/22 and now I get 404 on all websites. 

I have OAuth configured and working and disabled basic auth with cred command. I have switched back to basic just to test to see if it was an OAuth thing and it gets 404 on basic as well. Checked to make sure Traefik is listening and it is listening on ports 80, 443. No complaints from Traefik in the logs the only thing it logs on omni up is

traefik     | time="2022-10-16T23:53:00-05:00" level=info msg="Configuration loaded from flags."
traefik     | time="2022-10-16T23:55:29-05:00" level=info msg="Configuration loaded from flags."

All the containers start and are running in the background. I can see downloads going in the logs and everything working just no web access. 

only thing close to a sign of an issue are these lines but those containers start and are running. 

plex        | Critical: libusb_init failed
autoheal    | 17-10-2022 04:56:08 Container /sonarr (e5d0f3dce4b8) found to be unhealthy - Restarting container now with 10s timeout

 omni status
NAME                COMMAND                  SERVICE             STATUS              PORTS
autoheal            "/docker-entrypoint …"   autoheal            running (healthy)   
heimdall            "/init"                  heimdall            running             80/tcp, 443/tcp
nzbget              "/init"                  nzbget              running (healthy)   6789/tcp
oauth               "./traefik-forward-a…"   oauth               running             
ombi                "/init"                  ombi                running (healthy)   3579/tcp
omnimount           "bash -c /root/start…"   omnimount           running (healthy)   
plex                "/init"                  plex                running (healthy)   3005/tcp, 8324/tcp, 1900/udp, 32410/udp, 32400/tcp, 32412-32414/udp, 32469/tcp
radarr              "/init"                  radarr              running (healthy)   7878/tcp
sonarr              "/init"                  sonarr              running (healthy)   8989/tcp
tautulli            "/init"                  tautulli            running (healthy)   8181/tcp
traefik             "/entrypoint.sh --gl…"   traefik             running (healthy)   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp
watchtower          "/watchtower"            watchtower          running             8080/tcp

Just seeing that output there made me think maybe heimdall is stepping on traefik's toes running on 80 and 443.. removed it.. no go. still 404. 

also get this when I run omni down. 

jq: error (at <stdin>:0): Cannot iterate over null (null)
DNS deletion is disabled. No action performed.

and I noticed that cloudflare dns records weren't getting created.. probably realted to traefik not working. 

I'm out of ideas.. Let me know if you have any.. Thanks!

**Comment by wickedshrapnel** [comment]
OK got that fixed. Here is the process I had to do. 
Omni down
omni menu
remove traefik-cf
exit
omni home
cd configs/
mv traefik traefik.old
download setup again  
sudo wget tinyurl.com/omniSetup -O /tmp/setup && chmod 700 /tmp/setup && /tmp/setup
chmod fails on that so manually run sudo chmod 777 /tmp/setup
now type /tmp/setup and go through setup again
log off and back on
omni menu
readd traefik-cf
now when I went to any website I got invalid certificate
went to cloudflare control panel and changed SSL from Strict to Full
websites all work now but not sure how to get the Strict SSL back. I can live with full but if anyone knows how to get back to strict let me know.

**Comment by wickedshrapnel** [comment]
Just a note on websites not able to use strict SSL. Today I got notification from Cloudlare that a cert belonging to Cloudflare's edge has been deployed. I didn't do anything just happened in the background. Now I can run websites on strict again.

**Comment by falcomm6** [comment]
Hi @wickedshrapnel - just wanted to say THANK YOU for documenting this. Had the same thing with full disk. Life saver.

**Comment by elmerfreak** [comment]
Thanks for your help @wickedshrapnel 

It should be on the documentation @kelinger
