### ISSUE TITLE
Omnimount Configuration Options

### ISSUE THREAD

**Issue by Misterobots** [kelinger/OmniStream#29]
Hello! What would be the best approach to adjusting some of the Rclone / VFS settings within the Omnimount container? I apologize in advance if my language isn't the correct usage. Essentially I would like to adjust the VFS cache time. In your opinion, what would be "the best approach" for accomplishing this?
Thank you for your great work!

**Comment by mahogl** [comment]
Check out this closed issue, it should have the information you need.

https://github.com/kelinger/OmniStream/issues/17

**Comment by Misterobots** [comment]
Thank you so much. I apologize for not researching enough. I thought I had.  I will move forward based on the closed issue.  Thank you again!
