### ISSUE TITLE
container for service "omnimount" is unhealthy

### ISSUE THREAD

**Issue by SPECT3R-69** [kelinger/OmniStream#32]
Seems like this omnimount is a consitent problem creator.
No app would run / get deployed due to this.
Not so sure why but omnimount seems to be problem creator because no matter how many times i update and do omni up.
It still throws the error `container for service "omnimount" is unhealthy`

**Comment by SPECT3R-69** [comment]
`omnimount  | 
omnimount  | Configuration:
omnimount  | MERGEMOUNT=cloud
omnimount  | RCLONESERVICE=
omnimount  | RCLONEMOUNT=
omnimount  | UNSYNCED=unsynced
omnimount  | UPLOADCACHE=uploadcache
omnimount  | MEDIA=Media
omnimount  | TURBOMAX=20
omnimount  | One or more critical environment variables left undefined.
omnimount  | rclone v1.60.0
omnimount  | - os/version: debian 11.5 (64 bit)
omnimount  | - os/kernel: 5.4.0-125-generic (x86_64)
omnimount  | - os/type: linux
omnimount  | - os/arch: amd64
omnimount  | - go/version: go1.19.2
omnimount  | - go/linking: static
omnimount  | - go/tags: none
omnimount  | 
omnimount  | mergerfs version: 2.33.5
omnimount  | 
omnimount  | Starting vnstat
omnimount  | basename: missing operand
omnimount  | Try 'basename --help' for more information.
omnimount  | 
omnimount  | Configuration:
omnimount  | MERGEMOUNT=cloud
omnimount  | RCLONESERVICE=
omnimount  | RCLONEMOUNT=
omnimount  | UNSYNCED=unsynced
omnimount  | UPLOADCACHE=uploadcache
omnimount  | MEDIA=Media
omnimount  | TURBOMAX=20
omnimount  | One or more critical environment variables left undefined.
`

some logs i think could be of some help

**Comment by mahogl** [comment]
Looks like Rclone is not configured, can you provide the configuration of "/home/(username)/.config/rclone/rclone.conf" ? Just remember to clear out passwords/tokens/secrets info before you post it online.

**Comment by mahogl** [comment]
Great to hear that you figured it out
