### ISSUE TITLE
ERROR: for Container is unhealthy. ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by Abu3safeer** [kelinger/OmniStream#38]
Hello, 
I did get this when selecting any streaming component:
```
ERROR: for ... Container "..." is unhealthy.
ERROR: Encountered errors while bringing up the project.

```

I tried it with multiple components
![image](https://user-images.githubusercontent.com/12091003/206568231-5694fdf5-a983-42c3-911b-ddfa24806326.png)

**Comment by Abu3safeer** [comment]
this is status 
![image](https://user-images.githubusercontent.com/12091003/206568565-d67a76b9-f6c7-44f3-ac46-870506e8e588.png)

**Comment by Abu3safeer** [comment]
this is stats
![image](https://user-images.githubusercontent.com/12091003/206568868-7cc8dcb1-ad86-4f78-a53a-528a6eab3d7a.png)

**Comment by TechPerplexed** [comment]
Sounds like the Mount container isn't set up properly. What do you get when you type 
`omni home`
followed by
`ls mnt`
?

**Comment by Abu3safeer** [comment]
```cloud  uploadcache```

**Comment by Abu3safeer** [comment]
i tried installing nextcloud, it requires mariadb and radis, both if maria and radis installed succefully, but nexcloud didn't 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/12091003/206577136-0ba5c686-f9b7-4430-aee8-e942c3b03e1b.png">

**Comment by TechPerplexed** [comment]
Well, let's first sort your mount issue. Did you follow all the steps to set up Rclone? When you type `rclone configs` followed be `ls OmniMount`, do you see the file rclone.conf? Is it filled with the correct Rclone information?

**Comment by Abu3safeer** [comment]
I can see the rclone config, i can use ```omni menu``` then select  ```setups menus```  then ```redefine media directory``` i can see the file from google drive, to make sure it is correct, I created a folder in google drive then check ```redefine media directory``` and i can see the newly created folder with no issues.

**Comment by Abu3safeer** [comment]
by the way ```ls OmniMount``` didn't show anything, I am in main user folder

**Comment by TechPerplexed** [comment]
Sorry multitasking here... apologies. I meant what do you see when you type  `omni configs` followed by `ls omnimount`?

**Comment by Abu3safeer** [comment]
I see rclone.conf

**Comment by TechPerplexed** [comment]
And does it contain the same information as your original Rclone config file? What is the mount named?

**Comment by Abu3safeer** [comment]
yes the original information, the maont name is gd

**Comment by TechPerplexed** [comment]
So far, so good :) Let's try a system cleanup, see if that sorts it... try `omni refresh` followed `omni down`, then 'omni up". Does that bring back your mounts?

**Comment by Abu3safeer** [comment]
![image](https://user-images.githubusercontent.com/12091003/206580894-5b3c6848-46f3-4d31-bd2b-24a929cf85fd.png)

**Comment by TechPerplexed** [comment]
Thanks, I'm out of ideas for the time being, but will hand you over to @kelinger who I'm sure will be able to sort you out :)

**Comment by Abu3safeer** [comment]
I use oracle vps, it does require openning ports manually, does plex container need ports to be open to be healthy?

**Comment by kelinger** [comment]
There are a lot of things to discuss here so I'm going to take them apart and then recommend a process for finding what is preventing your startup.

Oracle:  For the most containers, the _only_ ports you need to open on an Oracle VPS will be the ssh port (which you obviously already have) and ports 80 and 443 for Traefik.  You do not need to open anything special for most containers with the exception of things like Torrent engines which need to go directly to the container (while the web interface will still go through the reverse web proxy).

It looks like, from your last screenshot, that you are getting the core components loaded.  Before we try any other containers, let's make sure that is the case.
```
omni down
omni components
```
When you're editing the components, make sure that all you have enabled is one version of Traefik (either the CloudFlare-aware version, traefik-cf, or the standard version, traefik) and OmniMount.  Everything else is just a distraction at this point.

Now, try to bring OmniStream back online:
```
omni up
```
Does it work?  Any errors?  If it doesn't report errors, then see if you can browse your cloud mount.
```
omni mounts
```
This command should make your current directory the one just above all the mounts.  You should see (if the default options were used) Cache, cloud, UploadCache, and the name you gave your cloud mount (eg, Google, gd, etc.).

If you can `cd` into the one named after your rclone service (let's say "Google" for the sake of this discussion) and see files, then things are looking good.  Go back to `omni mounts` and verify you can see the same files--and possibly more--in the directory called "cloud."  If so, this means that OmniMount is working and that you have the directory you will use for most things up.  This is the "Google" mounted drive overlain with local files pending upload as well as cached files like those you're downloading.

If the above is not working, there's no need to continue.  This needs to be resolved before we try to get NextCloud, Plex, or anything else up.  Let us know the results of the above and then we can proceed.

**Comment by Abu3safeer** [comment]
Ok, first I have enabled just those two components 
![image](https://user-images.githubusercontent.com/12091003/206651063-0b2a4aef-bf2f-443b-894f-3db8edeec4f9.png)

then bring it back online 

![image](https://user-images.githubusercontent.com/12091003/206651186-24251977-d161-40b0-bc2f-3cf15e1bbff8.png)

I only see those two 

![image](https://user-images.githubusercontent.com/12091003/206651394-4ad4c40c-934e-46fa-bde0-463cd2cdd4dc.png)

**Comment by kelinger** [comment]
Thanks for that update.

What do you see with:  `omni logs omnimount` ?
(control-c to exit)

**Comment by Abu3safeer** [comment]
Thank you @kelinger @TechPerplexed for helping me, I created a new fresh vps instance so I make sure it won't conflict with my other docker images.

first thing I do is installing OmniStream, everything was fine until the last step, I see this message
![image](https://user-images.githubusercontent.com/12091003/206659467-84035c31-03c9-4af3-8551-a66a5d59f578.png)

is it good for now?

**Comment by Abu3safeer** [comment]
As I see here
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04

``docker-compose`` become ``docker compose```, this might the cause of corrupted installation.

**Comment by kelinger** [comment]
Try running `update-compose`
