### ISSUE TITLE
Question - best method to delete cloud media

### ISSUE THREAD

**Issue by falcomm6** [kelinger/OmniStream#43]
Hi there,

Just a question. What is the best practice to delete media on the cloud? I have everything encrypted, so I cant do this through google drive. Are there any commands which work to delete a directory? Obviously being careful with this, lol

**Comment by kelinger** [comment]
Well, the shortest answer here would be to just use the Linux shell commands after browsing to the directory inside your mounted decrypted volume (eg, "Media/Movies" and then `rm -r Ghostbusters`)

But the longer answer is "it may depend on what you're deleting."  If its something managed by Radarr, Sonarr, or any other *arr, then deleting it through their interface is probably best (if you use the "rm" method, Radarr could just download it again).

Note that, in both cases, deletion is going to be instantly ran and not on a local copy.  This means that it could take a while for Linux to traverse a large structure of data as it is communicating constantly with Google (or whatever is hosting your data) while doing so.

**Comment by falcomm6** [comment]
Got it. Thank you. Just wasn't sure if you're meant to use rcpone commands or something.

Thanks !
