### ISSUE TITLE
Unable to setup Omnistream

### ISSUE THREAD

**Issue by geelenbert** [kelinger/OmniStream#45]
Server:
Hertzner VPS 
Ubuntu 22.04

Storage:
Hetzner Storagebox

I've created a Media folder in the root of the Hetzner Storagebox.

Following the setup steps as described on the website: 
[](https://www.omnistream.cloud/getting-started/installing-omnistream)

After setup is done:
```
=========================================================================
         OmniStream initial setup complete.  Please review!
=========================================================================

For a list of DNS entries needed, run:
        cat /home/minion/OmniStream/dns-report
          or
        omni dns

For installation report, run:
        cat /home/minion/OmniStream/install-report

=========================================================================
  Please log out and back into your server for changes to take effect
              or run "source ~/OmniStream/bin/omni_init"

Once you log back in, run the "omni menu" command to bring up options for
    customization and starting your containers for the first time.
=========================================================================

```

output of cat /home/minion/OmniStream/install-report:
```
Linux distribution is Ubuntu
Docker version 23.0.0, build e92dd87
Docker Compose version v2.15.1

Rclone:
Installed:  rclone v1.61.1
  Release:  rclone v1.61.1
     Beta:  rclone v1.62.0-beta.6728.04f7e5280

Rclone settings: /home/minion/.config/rclone/rclone.conf

OmniStream Config Files: /home/minion/OmniStream/configs
Traefik URL: traefik.<domain>.com

Rclone can be configured via the "rclone config" command.
or by restoring your configuration to the file:
/home/minion/.config/rclone/rclone.conf

Cloud directory: /home/minion/OmniStream/mnt/cloud
Media directory: /home/minion/OmniStream/mnt/cloud/Media

Customizations are in /home/minion/.config/omnistream.conf
```

Running the command: source ~/OmniStream/bin/omni_init

Now i can access the omni menu:
![image](https://user-images.githubusercontent.com/91923/217216891-4951d1f4-ee7a-4a5b-8487-0fdc2670a745.png)

Rclone.conf:
```
[hetznerbox]
type = sftp
host = uXXXXX.your-storagebox.de
user = uXXXXX
port = 23
pass = XXXXXXXXXXXXXXXX
```

omnistream.conf:
```
############################
#  Environment valriables  #
#     for OmniStream       #
############################

ADD_DNS=false
CF_CACHE=true
CF_EMAIL=
CF_KEY=
CONFIGS=/home/minion/OmniStream/configs
DELETE_DNS=false
DOWNLOADS=/home/minion/OmniStream/mnt/cloud/Downloads
GPUGIDS=44,109
GROUPID=1000
HOME=/home/minion
LOGS=/home/minion/OmniStream/logs
MYDOMAIN=<domain>.com
MYEMAIL=<EMAIL>@gmail.com
TIMEZONE=Europe/Amsterdam
USERID=1000
DIFFBAK="emby jellyfin plex"
TURBOMAX=20
AUTH=auth@docker

############################
#     Mount Variables      #
############################

MERGEMOUNT=/home/minion/OmniStream/mnt/cloud
RCLONEHOME=/home/minion/.config/rclone
RCLONESERVICE=
RCLONEMOUNT=
UNSYNCED=/home/minion/OmniStream/mnt/unsynced
UPLOADCACHE=/home/minion/OmniStream/mnt/uploadcache
MEDIA=/home/minion/OmniStream/mnt/cloud/Media

############################
#   Container/Host names   #
#     for OmniStream       #
#   Most people will not   #
# need to change anything. #
############################

APACHENAME=apache
BAZARRNAME=bazarr
DELUGENAME=deluge
EMBYNAME=emby
EMBYSTATNAME=embystat
HEALNAME=autoheal
HEIMDALLNAME=heimdall
HYDRANAME=hydra
JACKETTNAME=jackett
JELLYNAME=jellyfin
LIDARRNAME=lidarr
MARIADBNAME=mariadb
MEDUSANAME=medusa
MENU=www
MONITORRNAME=monitorr
MYSQLNAME=mysql
NETDATANAME=netdata
NEXTCLOUDNAME=nextcloud
NZBGETNAME=nzbget
OAUTHNAME=oauth
OAUTHID=none
OAUTHSECRET=none
OAUTHSUPERSECRET=<SECRET>
OAUTHUSER=<MAIL>@gmail.com
OMBINAME=ombi
OMNIHOME=/home/minion/OmniStream
ORGANIZRNAME=organizr
OVPNNAME=ovpn
PLEXCLAIM=
PLEXNAME=plex
PORTAINERNAME=portainer
POSTGRESNAME=postgres
PROWLARRNAME=prowlarr
QBITNAME=qbit
RADARRNAME=radarr
REDISCOMNAME=redis-commander
REDISNAME=redis
RTORRENTNAME=rtorrent
SABNZBDNAME=sabnzbd
SONARRNAME=sonarr
SPEEDNAME=speed
SQLSERVERNAME=sqlserver
TAUTULLINAME=tautulli
TRAEFIKNAME=traefik
TRANSNAME=transmission
USEOAUTH=false
WATCHNAME=watchtower

############################
#     Color Variables      #
############################

STD="[0m"
RED="[00;31m"
GREEN="[00;32m"
YELLOW="[00;33m"
BLUE="[00;34m"
MAGENTA="[00;35m"
PURPLE="[00;35m"
CYAN="[00;36m"
LGRAY="[00;37m"
LRED="[01;31m"
LGREEN="[01;32m"
LYELLOW="[01;33m"
LBLUE="[01;34m"
LMAGENTA="[01;35m"
LPURPLE="[01;35m"
LCYAN="[01;36m"
WHITE="[01;37m"
```

After a reboot the log files give the following results:
```
minion@minion:~$ omni status
NAME                IMAGE                                    COMMAND                  SERVICE             CREATED             STATUS                          PORTS
oauth               thomseddon/traefik-forward-auth:latest   "./traefik-forward-a…"   oauth               3 minutes ago       Up About a minute
omnimount           kelinger/omnimount:latest                "bash -c /root/start…"   omnimount           3 minutes ago       Restarting (1) 28 seconds ago
traefik             traefik:latest                           "/entrypoint.sh trae…"   traefik             3 minutes ago       Up About a minute (healthy)     0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp
```

Next i go too the omni menu -> 3 Setups menu -> 6 Redefine media directory -> Do you want to change to something else -> Yes
Nothing happens, i cant select anything new.

Changing the rclone config as suggested [here](https://www.reddit.com/r/hetzner/comments/x1p5ic/unstable_rclone_for_storage_box/): 
```
Rclone.conf:
[hetznerbox]
type = sftp
host = uXXXXX.your-storagebox.de
user = uXXXXX
port = 23
pass = XXXXXXXXXXXXXXXX
md5sum_command = md5sum
sha1sum_command = sha1sum
```

Reboot the system.

turbosync.log:
`OmniMount not running`
There are no other log files in the director: /home/minion/OmniStream/logs

I'm lost what i can do from here. It looks like an rclone issue or setup mismatch.

**Comment by geelenbert** [comment]
Additional, i've tried setting up with the followoing changes:
- Debian 10 and 11
- Rclone on FTP, SFTP and 
- Re running setups, and Rclone

nothing seems to work.

It is unclear for me what the directory structure should be in the root of the rclone mount. Also what directories i should create myself and which ones are created by omnistream.

**Comment by kelinger** [comment]
Are you sure you're using port 23?  This is usually the telnet port while SSH is over port 22.

**Comment by geelenbert** [comment]
Yes it is strange but correct: [link](https://docs.hetzner.com/robot/storage-box/access/access-ssh-rsync-borg/#rclone)
![image](https://user-images.githubusercontent.com/91923/217754551-548e6f0c-3bd5-47f9-b1cc-6dfae7f98f32.png)

I tried to set it up using an FTP connection to my Synology NAS. 
```
[synologyftp]
type = ftp
host = <DOMAIN>.com
user = minion
pass = <PASS>
```

This seems to work. 
```
minion@minion:~$ rclone lsd synologyftp:
          -1 2023-02-09 04:15:02        -1 Backups
          -1 2023-02-08 14:06:58        -1 Media
minion@minion:~$
```

Last night there has been a backup to my synology NAS:
![image](https://user-images.githubusercontent.com/91923/217755884-752b5b9a-6e2c-4744-a964-ac8da2e76931.png)

Containers seem running:
```
minion@minion:~$ omni status
NAME                IMAGE                                    COMMAND                  SERVICE             CREATED             STATUS                  PORTS
emby                emby/embyserver                          "/init"                  emby                19 hours ago        Up 18 hours (healthy)   1900/udp, 8096/tcp, 7359/udp, 8920/tcp
nzbget              lscr.io/linuxserver/nzbget               "/init"                  nzbget              19 hours ago        Up 18 hours (healthy)   6789/tcp
oauth               thomseddon/traefik-forward-auth:latest   "./traefik-forward-a…"   oauth               19 hours ago        Up 19 hours
omnimount           kelinger/omnimount:latest                "bash -c /root/start…"   omnimount           19 hours ago        Up 19 hours (healthy)
radarr              lscr.io/linuxserver/radarr:latest        "/init"                  radarr              19 hours ago        Up 18 hours (healthy)   7878/tcp
sonarr              lscr.io/linuxserver/sonarr               "/init"                  sonarr              19 hours ago        Up 18 hours (healthy)   8989/tcp
traefik             traefik:latest                           "/entrypoint.sh trae…"   traefik             19 hours ago        Up 19 hours (healthy)   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp
```

But now i get 404's on the services:
![image](https://user-images.githubusercontent.com/91923/217756270-e0463876-406a-4d0e-872b-9cea8e3baf3d.png)
![image](https://user-images.githubusercontent.com/91923/217756354-0820ab38-fcc4-426e-9e81-c752c3ab9323.png)

But emby works:
![image](https://user-images.githubusercontent.com/91923/217756422-a21ce17d-ed3e-4525-aefc-070a03b92d88.png)

**Comment by kelinger** [comment]
Did you remap your port on the Synology?  I have a Synology as well and port 22 is used for the SSH as well as SFTP (unless changed elsewhere).

You do seem to have gotten FTP working, though I'm not sure that's going to be the best fit for streaming.  If your Synology and your OmniStream server (which I'm assuming is different hardware) are on the same LAN, you may be able to skip all of this by simply mounting the Synology directly into the OmniStream server via NFS.  I actually do this today, though not for the streaming files, but rather to keep a local backup of my server (so I can do a quick restore without having to download--or keep downloading when I'm testing something--from Google each time).

**Comment by geelenbert** [comment]
No i have this on a VPS.

The FTP i tried is to my personal NAS on my local network. 
Overall i can;t get this to work. 

Omnimount container keeps restarting and stuff just not seems to work ok.

Omnistream should be a breeze to install and maintain, but i find it very hard to get up and running.

What kind of services do you use ?

**Comment by TechPerplexed** [comment]
What VPS are you using? I run Omni on a OneProvider dedicated server without any issues. Also tested it on various VPS systems, some only $2/month (obv

**Comment by TechPerplexed** [comment]
Closing this because it hasn't seen any activity for almost a month now - as always, feel free to reopen if new insights occur :)
