### ISSUE TITLE
Docker overlay2 filling up 100% disk space

### ISSUE THREAD

**Issue by meharrington90** [kelinger/OmniStream#47]
Hey there!

Love this software. Thanks for all your work.

I have noticed since I upgraded from Gooby to Omnistream that (what seems to be) my transcodes are filling up the below directory:

`/var/lib/docker/overlay2/`

I can watch this directory LIVE, increasing the size of my VPS HDD from 13% until 100%, and then killing any Plex streams once it reaches capacity. Only when I do an `omni down` and `omni up` can I clean up the overlay2 directory and begin watching streams again.

Not sure how to fix this? I tried to symlink the overlay2 directory to Google Drive, but it didn't work as planned.

NOTE: Also, unrelated, it seems everytime I take down omnistream and bring it back up, Tautulli also requires a full "wizard" reconfig right away.

**Comment by meharrington90** [comment]
Also, I have already done a complete `docker system prune -a` multiple times, with reboots and everything. Using `omni update` does not resolve the issue either. 

Seems that 1080p transcodes fill up space on the HDD MUCH faster than 720p streams. I can attest that I never had this issue when I was using Gooby.

**Comment by kelinger** [comment]
Assuming you're using the defaults, Plex and friends use /tmp on the host for their transcoding (mapped in Plex as /transcode).  This is outside of Docker and (again, by default) /tmp is cleared when the host is rebooted.

Additionally, rclone has a cache which OmniMount defaults to a max of 100G.  For most people, this is enough but for some, its too small or too big (this is all going to depend on how much space you have available, of course, on the host).  If you want to change these or several other OmniMount defaults, put a text file called `vfs.conf` in the /configs/omnimount subdirectory and assign these variables as needed:

```
VFSMAX=100G
VFSAGE=48h
VFSPOLL=5m
VFSREAD=2G
VFSCACHE=yes
```
(The defaults are shown above so if you are using those same values, there won't be any difference from simply not having that file present)

If you make changes, then stop/start OmniStream with `omni down` and then `omni up` commands.  You can also replace the `omni down` in this instance with `omni clean` which will take down OmniStream complete and purge all of Docker's cache, including downloaded containers (your personal files and container configurations are safe).

**Comment by meharrington90** [comment]
Thanks man. I just made the change to 50G now and did a full `omni clean` and `omni up`. I'm gonna mess around with streaming and various settings listed above for 24 hours and get back to you.
