### ISSUE TITLE
Nextcloud - healthy container but page stuck loading (not 404)

### ISSUE THREAD

**Issue by falcomm6** [kelinger/OmniStream#48]
Hi there,

ive recently set up nextcloud, but after about 30mins the webapp just stalls out. Do you know what could be causing this? The container is healthy.

Restarting the container does not help. However, omni down, then omni up fixes things temporarily. I tried with sqllite and mariadb to see if its the database, but the issue still occurs. Any pointers would be appreciated.

Thanks

**Comment by kelinger** [comment]
NextCloud is a nasty beast.  After turning it up for the first time, I have to immediately take it down and then fix the permissions for the files it created.  Make sure the nextcloud config directory and its contents are owned by "www-data"
```
omni configs
sudo chown -R www-data:www-data nextcloud
```
MariaDB and Redis also appear to need to be owned by "systemd-timesync" though I can't remember if I made that change myself or that's just how they were created.

**Comment by falcomm6** [comment]
Thanks Ken, appreciated
