### ISSUE TITLE
traefik 404s on Sonarr, Ombi, etc

### ISSUE THREAD

**Issue by christeasdale** [kelinger/OmniStream#50]
Debian 11 using traefik-CF, SSL certs good, containers healthy and running.  Good news is Plex and tautulli are working but all others "404 page not found" but if I ssh tunnel directly to Docker IP/port on my VPS for a service I can access it. (example ssh -L 8888:172.18.0.5:3579 chris@serverIP)  I am a noob on traefik.  Getting these errors in traefik logs.  Been researching for hours on closed issues but have not been able to fix this.  Help would be appreciated. thanks

time="2023-03-17T05:09:34-07:00" level=error msg="open /config/users: no such file or directory" routerName=https-ombi@docker entryPointName=https
time="2023-03-17T05:09:34-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=http routerName=ombi@docker
time="2023-03-17T05:09:34-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=http routerName=sonarr@docker
time="2023-03-17T05:09:35-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=http routerName=sonarr@docker
time="2023-03-17T05:09:35-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=http routerName=ombi@docker
time="2023-03-17T05:09:35-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=https routerName=https-ombi@docker
time="2023-03-17T05:09:35-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=https routerName=traefik@docker
time="2023-03-17T05:09:35-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=https routerName=https-sonarr@docker
time="2023-03-17T05:09:37-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=https routerName=traefik@docker
time="2023-03-17T05:09:37-07:00" level=error msg="open /config/users: no such file or directory" routerName=https-ombi@docker entryPointName=https
time="2023-03-17T05:09:37-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=https routerName=https-sonarr@docker
time="2023-03-17T05:09:37-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=http routerName=sonarr@docker
time="2023-03-17T05:09:37-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=http routerName=ombi@docker
time="2023-03-17T05:54:36-07:00" level=error msg="open /config/users: no such file or directory" routerName=https-sonarr@docker entryPointName=https
time="2023-03-17T05:54:36-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=https routerName=traefik@docker
time="2023-03-17T05:54:36-07:00" level=error msg="open /config/users: no such file or directory" routerName=sonarr@docker entryPointName=http
time="2023-03-17T05:56:06-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=https routerName=https-sonarr@docker
time="2023-03-17T05:56:06-07:00" level=error msg="open /config/users: no such file or directory" routerName=traefik@docker entryPointName=https
time="2023-03-17T05:56:06-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=https routerName=https-ombi@docker
time="2023-03-17T05:56:06-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=http routerName=sonarr@docker
time="2023-03-17T05:56:06-07:00" level=error msg="open /config/users: no such file or directory" entryPointName=http routerName=ombi@docker

**Comment by christeasdale** [comment]
I got traefik dashboard working and the two 404 containers (Sonarr and Gooby) both show the error 'middleware "auth@docker" does not exist' if that helps.

**Comment by christeasdale** [comment]
Okay after researching this issue.  i removed the following line in the respective yaml files for Ombi and Sonarr:

 - traefik.http.routers.ombi.middlewares=${AUTH}

Doing this resolved my 404 issues on both of them.  I believe this traefik command is somehow related to handling login credentials on web pages.  But I was still able to use the built in login functions on both Ombi and Sonarr.  If others wouldn't mind throwing up a temp docker to test this change we could propose a revision to @kelinger   A question is it safe to modify a preset yaml file?  I assume they might get ridden over during an update?

**Comment by kelinger** [comment]
@christeasdale - if you modify a file, it will NOT get overwritten.  The bad news is that it won't get updated, either.  There are a couple of ways to do this though:

* Edit the file directly.  It will remain yours and won't update with the exception of running the undocumented `omni reset` command which purposely forces OmniStream to update everything (not the config files but it forces all the code and containers to match the repository).
* Copy the file you want to edit to another file in the 800 range.  EG:  copy 301-radarr.yaml to 801-radarr.yaml.  The 800 range is deliberately exempt from updates and is a place where you can put your own custom containers (like a modified Radarr in this example) or containers not part of the project.  Even an `omni reset` won't delete/change these files.  Naturally, they won't be updated, either.  So, if you later find your personal version of Radarr stops working one day, check the "real" one (301) to see if we've made any changes that you need to copy through to yours.

**Comment by christeasdale** [comment]
Thanks for getting back to me.  As I mentioned the change above I made to 308-ombi.yaml to make it not 404 ... When I run "omni update" my modified 308-ombi.yaml in the "OmniStream/components" folder is replaced with the original from Github?

**Comment by kelinger** [comment]
So its looking like the changes made to adapt to the updated FuserMount may not have worked correctly on new installations.  I'm going to have to build a test system and try everything from the start.  I do know that mine and @TechPerplexed got it to work with those changes and I know a few others have commented that they have as well but none of these are through a completely clean installation.

Did you ever get around those containers not starting, @christeasdale ?

**Comment by christeasdale** [comment]
The containers were starting I just wasn't able to communicate with them...

removing 
"traefik.http.routers.ombi.middlewares=${AUTH}"  and similar for Sonarr YAML they both then work as far as I can tell perfectly.  Can't say I understand the traefik command in question but it doesn't seem to be needed.  Up to you if you think those YAML files need this change.  I did have to move them to 800 range because a "omni update" writes over any changes to running containers in normal range.  But if they are stopped changes aren't written over.
