### ISSUE TITLE
Omnimout error: failed to start, container is unhealthy

### ISSUE THREAD

**Issue by ffwjb** [kelinger/OmniStream#53]
Since the last rclone update i've bricked my Gooby installation: looping on mounting.
edit: i've updated to fuse3 and it's al working again. So I'm back to Gooby.

I upgraded to Omni but no succes either, constant error on Omnimout so none of my media container (Plex, Sonarr, Radarr) wont come up.

Wiped my server, started all fresh.
Installed Omni, setup went fine, untill starting the containers. I still get an error on creating Omnimount.
Rclone is working now, I can see my Gdrive file on the mount.

Any help on how to get Omnimount to work?

**Comment by kelinger** [comment]
We believe the rclone issue was resolved about a week ago with an update to OmniStream so that it uses Fuse3 instead of Fuse2.  It may take an `omni update` followed by a down, logout, login, up but things should be working again.

**Comment by ffwjb** [comment]
I could not get it working, multiple times omni update/up/down, reboot server, wiped server, etc.
So I installed Gooby again, manual update to fuse 3 and rclone started working again lucky me.

So for now i'm happy all is working again, but I just can't wrap my head aroud the fact I didn't get Omni to work.

**Comment by ASchluterman** [comment]
I'm going to piggy back off of this thread as it most closely relates to the issues I seem to be facing. I'd been using Gooby for several years now, so first want to say how appreciative of all the effort put into the lifespan of that.

Like OP, I'd managed to cripple my setup and when I started digging in I found your new platform. Started with a fresh debian install and then began the process with Omni. However, I cannot seem to get any of the containers to be active aside from Traefik and Omnimount. When I select new active components and then run omni up, nothing happens.

I've tried the above, as well as starting from scratch a few times with no success.

Appreciate your guidance.

**Comment by ASchluterman** [comment]
Also spend some time looking at issue #49 and comments there.

I have updated, cleaned, up, down, whole 9 yards. Fusemount Version Seems to still be 2.9.9. Only strange bit is when I put in 

docker exec -ti omnimount fusermount -V

![image](https://user-images.githubusercontent.com/51297624/230198442-c1dec8b2-6fe3-4719-8fb7-b0ce84b5fc76.png)

**Comment by roubachof** [comment]
hey @ffwjb !
I have the exact same issue, and followed the exact same path :)
Lost an entire day trying to make work omni, with multiple vps reinstall, with cloudfare/wo, it's a total mess :)
when you say "i've updated to fuse3 and it's al working again. So I'm back to Gooby."
did you only apt install fuse3?
or did you also removed the 2.9.9?

**Comment by ffwjb** [comment]
Hey @roubachof I only did: sudo apt-get -y install fuse3

**Comment by roubachof** [comment]
ty @ffwjb ! I had a user permission issue with mergefs, but now thanks to @TechPerplexed everything is working again.
Will stay with gooby till the end of time x)

**Comment by kelinger** [comment]
There are two fuses used.  There's the one on the server (host) machine which really is only used during the setup.  The rest of the time, everything runs inside OmniStream (using the OmniMount container) and it is OmniMount that needed to be upgraded to Fuse3 (which was published after a day or two).
