### ISSUE TITLE
Media Variable

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#6]
During setup when offered to set the media folder for the ${Media} variable it doesn’t keep the change. It still mounts as /cloud/Media instead of the location I set. I can’t rename my file structure at this time because I’m in the process of pulling 45TB off of GSuite to bare metal. I got tired of bumping into the new file access rules they’ve put in. In another week I’ll have it done and can rename my top folder and make things easier for myself. In the mean time I’ve had to do some creative mount options with rclone and rsync options. To keep access to my media content while I wait for everything to synch up to local storage. I’ve left deluge un-configured to prevent new content from being uploaded.

@kelinger sorry you are getting double hit with these issues. I mistakenly posted them on @TechPerplexed Gooby GitHub Omni branch instead of here. Again my apologies.

**Comment by shadowsbane0** [comment]
Not a bug. When I re=ran the setup script it correctly mapped this time for a custom media folder.

**Comment by TechPerplexed** [comment]
Haha either that or our genius fixed it in the meantime 😂
