### ISSUE TITLE
Containers are dropping out with exit 128

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#65]
I’m getting constant 128 errors and my containers shutting down. I don’t understand it. Most of the articles I’ve research want to point to out of memory as an issue. That isn’t an issue on this host. The guest currently as 64GB RAM assigned, 12 Cores, and a 16GB Swap partition just for shits. I’m currently operating 31 containers with your build. HTOP and NetData don’t show a trend line even coming close to it being a resource issue. I don’t see anything in the logs that even tell me why the shutdown. Just starts shutdown processes in the log file.

**Comment by kelinger** [comment]
What host is this on?  I have found a couple hosting services that run on shared hardware that kills off tasks the go above 20 or 30% CPU for more than x seconds.  Yeah, not good.

**Comment by shadowsbane0** [comment]
It was VM Mem resourcing issue.
