### ISSUE TITLE
Rclone with local mount - unhealthy

### ISSUE THREAD

**Issue by falcomm6** [kelinger/OmniStream#66]
Hi there!
Thanks as always for this app, it really is a great hobby. With doomsday approaching for Google Drive, I need to say goodbye to my cloud server. I could move elsewhere, but I feel its just a matter of  time it all gets cracked down.

I want to set up Omnistream the old fashioned way with local storage. For some reason I cant get omnimount to play ball with a local device. Im probably missing something, but any tips?

Cheers,

**Comment by falcomm6** [comment]
All good I worked out what I need to do. Sorry !

**Comment by mahogl** [comment]
@falcomm6 can i ask you what you did to make it work, i am having som issues with the same. I have migrated from google drive to local nas and i am accessing my share with nfs. But looks like i am running into a permission issue. The NFS mount works fine, but when i try to add it to rclone and omnistream the folder shows up empty,

So if you could share some info on what you did to make it work it would be greatly appreciated.
