### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#7]
I was watching omni update run and at the end saw line pop up saying pveam command not found. I wasn't familiar with it so I looked it up. Are you running on a Proxmox based host? If so how is it working for you? I'm curious because after a brief lookup I see that it appears to be a linux equivalent of esxi. Unfortunately I'm all too intimate with esxi in my former work. I didn't so much linux work then so now I dabble and tinker almost exclusively in linux just to sate my curiosity. 

The main reason I ask is I've put esxi on a system before but since they are laptops there were some limitations - mostly because at the time I purchased them mainly for gaming purposes and needed the graphics capability and esxi really didn't support graphics in its hypervisor. I then turned to using Workstation for any VM "take home work" that I needed to do. Somethings have improved over the years but I don't game as much or any really these days.

I've mentioned before the donor host I'm using is getting a little old to be running what I'm putting it through. I suppose I could get a Dell R420 pretty cheap (for me) but then I would have to put it in my basement because the fan noise would drive my wife nuts. Anyway I have the twin little brother of my current host that is smaller but has more and faster ram. It gives me 64gb in a laptop format vs the 32gb max in its big brother.  I've been considering promoting it to my primary host for this project because it also has a two year newer processor as well. Other specs are similar to original host and since it isn't tpm v2 capable I can't update to "no-win v11". I'm close to pulling the trigger on new system for my Windows based programs Proxmox could be a candidate for the base system of the new donor host if there are some applicable benefits for this project. It's literally the only thing my host does at the moment. I'm thinking some other things for the future for my business which is why I'm asking. Proxmox would enable me to isolate work and fun.

This is more back end talk so feel free to reply and remove this post.

**Comment by kelinger** [comment]
First, thanks for catching the "pveam" as that was a leftover from my personal setup.  It's the sort of thing that belongs in the plugins where you can augment your own customizations into the normal OmniStream processes.  It has since been removed.

As for Proxmox, I have been happy with it.  It supports two types of virtualization:  QEMU and LXC.  QEMU is your typical virtualization, like that with VMware while LXC is a form of containerization (albeit, not Docker).  I've been using Proxmox for about 6 years now and have been pretty happy with it.  Yes, ESXi is a bit more refined and you can also use the desktop software as a client.  While not open-source, there is a free version of ESXi but the features included seem to change with each version.

Proxmox, on the other hand, can be installed from CD or on top of an existing Debian install.  This means that you can pretty much get it up and running on nearly any hosted system.  While I have successfully installed ESX on a hosted system, the caveat is that you end up having the Internet as your management network which is, to put it bluntly, very insecure.  You also completely lose that Internet IP for that management network and that means you are buying at least one other IP which those hosts sell at a premium.  Finally, since Proxmox runs on Debian, all of my Docker containers also run on the host--not in a virtualed system--whereas your first task on ESX would be to create virt to run OmniStream.

**Comment by shadowsbane0** [comment]
Thanks for the tips on ProMax. It sounds like something I’ll work on a latter in a few months. Gonna be busy with other things to pick up something new right this moment - other than this project I mean. :)


Sent from my iPad

On Mar 10, 2022, at 22:43, Ken Linger ***@***.***> wrote:

﻿

First, thanks for catching the "pveam" as that was a leftover from my personal setup. It's the sort of thing that belongs in the plugins where you can augment your own customizations into the normal OmniStream processes. It has since been removed.

As for Proxmox, I have been happy with it. It supports two types of virtualization: QEMU and LXC. QEMU is your typical virtualization, like that with VMware while LXC is a form of containerization (albeit, not Docker). I've been using Proxmox for about 6 years now and have been pretty happy with it. Yes, ESXi is a bit more refined and you can also use the desktop software as a client. While not open-source, there is a free version of ESXi but the features included seem to change with each version.

Proxmox, on the other hand, can be installed from CD or on top of an existing Debian install. This means that you can pretty much get it up and running on nearly any hosted system. While I have successfully installed ESX on a hosted system, the caveat is that you end up having the Internet as your management network which is, to put it bluntly, very insecure. You also completely lose that Internet IP for that management network and that means you are buying at least one other IP which those hosts sell at a premium. Finally, since Proxmox runs on Debian, all of my Docker containers also run on the host--not in a virtualed system--whereas your first task on ESX would be to create virt to run OmniStream.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkelinger%2FOmniStream%2Fissues%2F7%23issuecomment-1064742784&data=04%7C01%7C%7C80a90a33592d4610c26d08da03114d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825670089224987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0aC%2Fa8dDMlo2r62W4pVU2jVfTxtj5QLRg44KGQMqKUs%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGC5UY3CVWEMA45F33TU7K6N5ANCNFSM5QMZBTYA&data=04%7C01%7C%7C80a90a33592d4610c26d08da03114d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825670089224987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E%2BrWw7KyOhJYJlmZJiEfOC6fBzrlJ1uC7xZmJ8vDoMs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C80a90a33592d4610c26d08da03114d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825670089224987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oCatuYIubwqAR1EIAT4PYUm5FLtSxq5k9L3od7dx1Q8%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C80a90a33592d4610c26d08da03114d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825670089224987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yMmbtIfTiQ9ZJ5s%2Fm822TnKB3Rozp73nCrZoU94c7LQ%3D&reserved=0>.

**Comment by shadowsbane0** [comment]
Thanks Apple for telling me again what I meant to write. The word of the day is Proxmox you nosy skank.

Sent from my iPad

On Mar 10, 2022, at 23:19, Brian Curry ***@***.***> wrote:

﻿ Thanks for the tips on ProMax. It sounds like something I’ll work on a latter in a few months. Gonna be busy with other things to pick up something new right this moment - other than this project I mean. :)


Sent from my iPad

On Mar 10, 2022, at 22:43, Ken Linger ***@***.***> wrote:

﻿

First, thanks for catching the "pveam" as that was a leftover from my personal setup. It's the sort of thing that belongs in the plugins where you can augment your own customizations into the normal OmniStream processes. It has since been removed.

As for Proxmox, I have been happy with it. It supports two types of virtualization: QEMU and LXC. QEMU is your typical virtualization, like that with VMware while LXC is a form of containerization (albeit, not Docker). I've been using Proxmox for about 6 years now and have been pretty happy with it. Yes, ESXi is a bit more refined and you can also use the desktop software as a client. While not open-source, there is a free version of ESXi but the features included seem to change with each version.

Proxmox, on the other hand, can be installed from CD or on top of an existing Debian install. This means that you can pretty much get it up and running on nearly any hosted system. While I have successfully installed ESX on a hosted system, the caveat is that you end up having the Internet as your management network which is, to put it bluntly, very insecure. You also completely lose that Internet IP for that management network and that means you are buying at least one other IP which those hosts sell at a premium. Finally, since Proxmox runs on Debian, all of my Docker containers also run on the host--not in a virtualed system--whereas your first task on ESX would be to create virt to run OmniStream.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkelinger%2FOmniStream%2Fissues%2F7%23issuecomment-1064742784&data=04%7C01%7C%7C80a90a33592d4610c26d08da03114d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825670089224987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0aC%2Fa8dDMlo2r62W4pVU2jVfTxtj5QLRg44KGQMqKUs%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGC5UY3CVWEMA45F33TU7K6N5ANCNFSM5QMZBTYA&data=04%7C01%7C%7C80a90a33592d4610c26d08da03114d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825670089224987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E%2BrWw7KyOhJYJlmZJiEfOC6fBzrlJ1uC7xZmJ8vDoMs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C80a90a33592d4610c26d08da03114d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825670089224987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oCatuYIubwqAR1EIAT4PYUm5FLtSxq5k9L3od7dx1Q8%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C80a90a33592d4610c26d08da03114d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825670089224987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yMmbtIfTiQ9ZJ5s%2Fm822TnKB3Rozp73nCrZoU94c7LQ%3D&reserved=0>.
