### ISSUE TITLE
Odd Behavior With Omnimount

### ISSUE THREAD

**Issue by Misterobots** [kelinger/OmniStream#74]
I have done my best to try and troubleshoot the odd behavior happening. 
Testing scenarios: 
Full OmniStream Stack - Fresh rebuild
Omnimount only - Fresh rebuild
Pre-setup of Rclone Mount
Fresh Rclone drive/remotes
Imported Rclone drive/remotes

I am having an odd issue with Omnimount/Rclone. Going through setup, there are no errors in any of the logs (omni or rclone), but when setting up Omnimount, only the "cloud" mount is visible. I can see the subdirectories (Downloads: empty, Media: empty), but no "Media", "unsynched", or "uploadcache".  

When I exec into the omnimount container, I can see all of the directories, and I can see that Media is successfully linked to the rclone mount ( I can see drive contents), but that's as far as it gets.

I thought maybe some odd issue with mount binding and contents being "obscured" but everything seems set correctly. I am happy to provide any info or additional logs you may want. I appreciate that assistance as always.

![image](https://github.com/kelinger/OmniStream/assets/9805557/4f4e95d7-035e-44f3-951e-5a82bdc56c51)
Omnimount container

![image](https://github.com/kelinger/OmniStream/assets/9805557/3ccf9fbd-571a-4f81-ac72-bf22b862ffe0)
Host

**Comment by Misterobots** [comment]
Omnimout log

omnimount  | rclone v1.64.0
omnimount  | - os/version: debian 12.1 (64 bit)
omnimount  | - os/kernel: 5.15.0-84-generic (x86_64)
omnimount  | - os/type: linux
omnimount  | - os/arch: amd64
omnimount  | - go/version: go1.21.1
omnimount  | - go/linking: static
omnimount  | - go/tags: none
omnimount  |
omnimount  | mergerfs v2.37.1
omnimount  |
omnimount  | https://github.com/trapexit/mergerfs
omnimount  | https://github.com/trapexit/support
omnimount  |
omnimount  | ISC License (ISC)
omnimount  |
omnimount  | Copyright 2023, Antonio SJ Musumeci <trapexit@spawn.link>
omnimount  |
omnimount  | Permission to use, copy, modify, and/or distribute this software for
omnimount  | any purpose with or without fee is hereby granted, provided that the
omnimount  | above copyright notice and this permission notice appear in all
omnimount  | copies.
omnimount  |
omnimount  | THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
omnimount  | WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
omnimount  | WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
omnimount  | AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
omnimount  | DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
omnimount  | PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
omnimount  | TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
omnimount  | PERFORMANCE OF THIS SOFTWARE.
omnimount  |
omnimount  |
omnimount  | Starting vnstat
omnimount  | No interfaces found in database, adding available interfaces...
omnimount  | Interface "eth0" added with 10000 Mbit bandwidth limit.
omnimount  | -> 1 new interface found.
omnimount  | Limits can be modified using the configuration file. See "man vnstat.conf".
omnimount  | Unwanted interfaces can be removed from monitoring with "vnstat --remove".
omnimount  |
omnimount  | Configuration:
omnimount  | MERGEMOUNT=cloud
omnimount  | RCLONESERVICE=Media
omnimount  | RCLONEMOUNT=Media
omnimount  | UNSYNCED=unsynced
omnimount  | UPLOADCACHE=uploadcache
omnimount  | USENFS=false
omnimount  | NFSREMOTE=
omnimount  | NFSLOCAL=
omnimount  | MEDIA=Media
omnimount  | TURBOMAX=20
omnimount  | LOCAL=Media
omnimount  | Adding group `omniuser' (GID 1000) ...
omnimount  | Done.
omnimount  | Adding user `omniuser' ...
omnimount  | Adding new user `omniuser' (1000) with group `omniuser (1000)' ...
omnimount  | Creating home directory `/home/omniuser' ...
omnimount  | Copying files from `/etc/skel' ...
omnimount  | Adding new user `omniuser' to supplemental / extra groups `users' ...
omnimount  | Adding user `omniuser' to group `users' ...
omnimount  | Cleaning up leftovers
omnimount  | Starting services
omnimount  | VFSMAX=100G
omnimount  | VFSAGE=48h
omnimount  | VFSPOLL=5m
omnimount  | VFSREAD=2G
omnimount  | VFSCACHE=yes
omnimount  | DIRCACHE=96h
omnimount  | NFS Disabled
omnimount  | mkdir -p /mnt/Media
omnimount  | OmniMount Caching: enabled
omnimount  | {
omnimount  |    "jobid": 1
omnimount  | }
omnimount  |
omnimount  | Startup complpete

**Comment by kelinger** [comment]
I was traveling last week but finally got a chance to read through your post this weekend.

That's very odd.  Towards the end of the log file, you can see the "jobid = 1" which tells me that the remotely mounted service is up and that the directory scan has started.  If the rclone mount failed, it would mean that the rclone daemon isn't running and this background task would have failed.

Based on the data in the logs, I'm assuming that the entry in your rclone config for your cloud service (Google, Dropbox, etc.) is called "Media" correct?

**Comment by meharrington90** [comment]
This is the same issue I'm having from the other ticket.

**Comment by kelinger** [comment]
OK, but in the other thread, your settings show as:

```
omnimount | MERGEMOUNT=cloud
omnimount | RCLONESERVICE=google
omnimount | RCLONEMOUNT=google
omnimount | UNSYNCED=unsynced
omnimount | UPLOADCACHE=uploadcache
```

and in this thread they show as

```
omnimount | MERGEMOUNT=cloud
omnimount | RCLONESERVICE=Media
omnimount | RCLONEMOUNT=Media
omnimount | UNSYNCED=unsynced
omnimount | UPLOADCACHE=uploadcache
```

So I wanted to check.  If this is correct, then I'll move on.  If not, the first thing I'd check is to make sure the rclone.conf in the /configs for OmniMount is accurate.

**Comment by meharrington90** [comment]
Yep @Misterobots is having the same issue is me, I just piped in on this ticket. I'm assuming his rclone mount is just named "Media" while I named mine "google"

**Comment by kelinger** [comment]
OK, duh... missed that.

I just recompiled OmniMount with the newer Debian software and an updated Rclone.  It's a long shot, but could you try to refresh it (`omni update`) ?

**Comment by meharrington90** [comment]
Nogo. Did a full `sudo apt update && sudo apt upgrade` and reboot as well.

```shell
omnimount      | Configuration:
omnimount      | MERGEMOUNT=cloud
omnimount      | RCLONESERVICE=google
omnimount      | RCLONEMOUNT=google
omnimount      | UNSYNCED=unsynced
omnimount      | UPLOADCACHE=uploadcache
omnimount      | USENFS=false
omnimount      | NFSREMOTE=
omnimount      | NFSLOCAL=
omnimount      | MEDIA=Media
omnimount      | TURBOMAX=20
omnimount      | LOCAL=google
omnimount      | Adding group `omniuser' (GID 1000) ...
omnimount      | Done.
omnimount      | Adding user `omniuser' ...
omnimount      | Adding new user `omniuser' (1000) with group `omniuser (1000)' ...
omnimount      | Creating home directory `/home/omniuser' ...
omnimount      | Copying files from `/etc/skel' ...
omnimount      | Adding new user `omniuser' to supplemental / extra groups `users' ...
omnimount      | Adding user `omniuser' to group `users' ...
omnimount      | Cleaning up leftovers
omnimount      | Starting services
omnimount      | VFSMAX=100G
omnimount      | VFSAGE=48h
omnimount      | VFSPOLL=5m
omnimount      | VFSREAD=2G
omnimount      | VFSCACHE=yes
omnimount      | DIRCACHE=96h
omnimount      | NFS Disabled
omnimount      | mkdir -p /mnt/google
omnimount      | OmniMount Caching: enabled
omnimount      | {
omnimount      |        "jobid": 1
omnimount      | }
omnimount      | 
omnimount      | Startup complpete
^Ccanceled
plexabyte@Plexabyte:~/OmniStream/mnt$ ls
cloud
plexabyte@Plexabyte:~/OmniStream/mnt$
```

**Comment by Misterobots** [comment]
> I was traveling last week but finally got a chance to read through your post this weekend.
> 
> That's very odd. Towards the end of the log file, you can see the "jobid = 1" which tells me that the remotely mounted service is up and that the directory scan has started. If the rclone mount failed, it would mean that the rclone daemon isn't running and this background task would have failed.
> 
> Based on the data in the logs, I'm assuming that the entry in your rclone config for your cloud service (Google, Dropbox, etc.) is called "Media" correct?

That's correct.  Media is the remote name. 

You are also correct that within the Omnimount container, the storage Remote is fully accessible, visibly correct, and operates as I normally see. Outside the container, the "Media" directory is all that shows, and it's empty from the host view.

**Comment by robnester** [comment]
I'm seeing similar behavior with a fresh installation on a fresh installation of Debian.

```
$ omni logs omnimounts
omnimount  | rclone v1.64.2
omnimount  | - os/version: debian 12.2 (64 bit)
omnimount  | - os/kernel: 6.1.0-13-amd64 (x86_64)
omnimount  | - os/type: linux
omnimount  | - os/arch: amd64
omnimount  | - go/version: go1.21.3
omnimount  | - go/linking: static
omnimount  | - go/tags: none
omnimount  | 
omnimount  | mergerfs v2.37.1
omnimount  | 
omnimount  | https://github.com/trapexit/mergerfs
omnimount  | https://github.com/trapexit/support
omnimount  | 
omnimount  | ISC License (ISC)
omnimount  | 
omnimount  | Copyright 2023, Antonio SJ Musumeci <trapexit@spawn.link>
omnimount  | 
omnimount  | Permission to use, copy, modify, and/or distribute this software for
omnimount  | any purpose with or without fee is hereby granted, provided that the
omnimount  | above copyright notice and this permission notice appear in all
omnimount  | copies.
omnimount  | 
omnimount  | THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
omnimount  | WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
omnimount  | WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
omnimount  | AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
omnimount  | DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
omnimount  | PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
omnimount  | TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
omnimount  | PERFORMANCE OF THIS SOFTWARE.
omnimount  | 
omnimount  | 
omnimount  | Starting vnstat
omnimount  | No interfaces found in database, adding available interfaces...
omnimount  | Interface "eth0" added with 10000 Mbit bandwidth limit.
omnimount  | -> 1 new interface found.
omnimount  | Limits can be modified using the configuration file. See "man vnstat.conf".
omnimount  | Unwanted interfaces can be removed from monitoring with "vnstat --remove".
omnimount  | 
omnimount  | Configuration:
omnimount  | MERGEMOUNT=cloud
omnimount  | RCLONESERVICE=gdrive
omnimount  | RCLONEMOUNT=gdrive
omnimount  | UNSYNCED=unsynced
omnimount  | UPLOADCACHE=uploadcache
omnimount  | USENFS=false
omnimount  | NFSREMOTE=
omnimount  | NFSLOCAL=
omnimount  | MEDIA=Media
omnimount  | TURBOMAX=20
omnimount  | LOCAL=gdrive
omnimount  | Adding group `omniuser' (GID 1000) ...
omnimount  | Done.
omnimount  | Adding user `omniuser' ...
omnimount  | Adding new user `omniuser' (1000) with group `omniuser (1000)' ...
omnimount  | Creating home directory `/home/omniuser' ...
omnimount  | Copying files from `/etc/skel' ...
omnimount  | Adding new user `omniuser' to supplemental / extra groups `users' ...
omnimount  | Adding user `omniuser' to group `users' ...
omnimount  | Cleaning up leftovers
omnimount  | Starting services
omnimount  | VFSMAX=100G
omnimount  | VFSAGE=48h
omnimount  | VFSPOLL=5m
omnimount  | VFSREAD=2G
omnimount  | VFSCACHE=yes
omnimount  | DIRCACHE=96h
omnimount  | NFS Disabled
omnimount  | mkdir -p /mnt/gdrive
omnimount  | OmniMount Caching: enabled
omnimount  | {
omnimount  |    "jobid": 1
omnimount  | }
omnimount  | 
omnimount  | Startup complpete
```

On the server:
```
user@host:~/OmniStream/mnt$ ls
cloud
user@host:~/OmniStream/mnt$ ls cloud/
Downloads
```

One the omnimount container:
```
root@omnimount:~# cd /mnt/
root@omnimount:/mnt# ls -alh
total 16K
drwxr-xr-x 6 omniuser omniuser 4.0K Oct 24 14:57 .
drwxr-xr-x 1 root     root     4.0K Oct 24 14:57 ..
drwxrwxrwx 1 omniuser omniuser    0 Oct 24 14:57 cloud
drwxrwxrwx 1 omniuser omniuser    0 Oct 24 14:57 gdrive
drwxr-xr-x 2 omniuser omniuser 4.0K Oct 24 14:57 unsynced
drwxr-xr-x 3 omniuser omniuser 4.0K Oct 24 14:57 uploadcache
root@omnimount:/mnt# ls -alh gdrive/
total 4.0K
drwxrwxrwx 1 omniuser omniuser    0 Oct 24 14:57 .
drwxr-xr-x 6 omniuser omniuser 4.0K Oct 24 14:57 ..
drwxrwxrwx 1 omniuser omniuser    0 Oct 24 14:57 Media
root@omnimount:/mnt# ls -alh cloud/
total 8.0K
drwxrwxrwx 1 omniuser omniuser    0 Oct 24 14:57 .
drwxr-xr-x 6 omniuser omniuser 4.0K Oct 24 14:57 ..
drwxr-xr-x 2 omniuser omniuser 4.0K Oct 24 14:57 Downloads
drwxrwxrwx 1 omniuser omniuser    0 Oct 24 14:57 Media
```

**Comment by Misterobots** [comment]
I will add that mounting Remotes with Rclone, outside of the container, work as expected. There is just no "tie" in to the core function with Omnimount. All signs point to an issue with the container implementation, but if there is, I cannot find it at all.

**Comment by meharrington90** [comment]
Yep I was able to mount it outside of the container as well. If I had to guess, it would be an issue with the config for the reverse bind from container to host. Although I'm not skilled enough in Docker to troubleshoot that.

**Comment by Misterobots** [comment]
> Yep I was able to mount it outside of the container as well. If I had to guess, it would be an issue with the config for the bind from container to host. Although I'm not skilled enough in Docker to troubleshoot that.
> 
> This section is worth a look though, in the `003-omnimount.yaml` file:
> 
> ```shell
>     volumes:
>       - ${CONFIGS}/omnimount:/config
>       - ${LOGS}:/logs
>       - ${OMNIHOME}/healthchecks/omnimountcheck:/omnimountcheck
>       - type: bind
>         source: ${OMNIHOME}/mnt
>         target: /mnt
>         bind:
>           propagation: shared
> ```

I did some investigation into exactly that. Unfortunately, I wasn't able to come to any conclusions. The shared propagation designation and binding to a folder should allow both the host and container to see and interact with all directories in "/mnt".  Initially I played around with that bind, but I was not able to affect any positive change.

**Comment by kelinger** [comment]
I'm creating a test box.  I've downloaded the latest Debian Bookworm DVD and will install it from it.  I'll be running "apt update" and installing "sudo," but that's the only prep I'm doing before trying the OmniStream installation.

Does anyone in this thread believe this will NOT mirror what they've done?

**Comment by robnester** [comment]
This mirrors my process.

**Comment by Misterobots** [comment]
> This mirrors my process.

Same. Please let us know if we can do anything to assist further.

**Comment by kelinger** [comment]
Well, if there's good news, its that I was able to replicate the issue on my test box.

The bad news is that there is no logical reason why this should be happening.  My "production" box and the test box run Debian 12.2.  Both are running identical versions of Docker and Docker Compose.  Both are also running the same version of Rclone and fuse.

This is going to take more time to solve.

**Comment by kelinger** [comment]
For those interested in more details, the mount between the host and OmniMount is coming up and it is indeed showing that propagation of the sub-directories of "/mnt" is enabled.  It's just not... propagating.

```
            {
                "Type": "bind",
                "Source": "/home/kelinger/OmniStream/mnt",
                "Destination": "/mnt",
                "Mode": "rw,rshared",
                "RW": true,
                "Propagation": "rshared"
            }
```

**Comment by meharrington90** [comment]
@kelinger Hmmm. Do you think this is related to the change you made last month regarding NFS somehow? My installation broke (on both servers) when that update was posted. It was in the previous ticket I commented on.

**Comment by kelinger** [comment]
You'd think that, right?  But rclone is mounting things inside the container and so is NFS.  The difference is that NFSs mounts make it back to the host while Rclone's do not.

I'm looking into it being potentially fuse-related right now.

**Comment by kelinger** [comment]
@meharrington90 Can you try the following on your host?
```
omni down
sudo apt remove fuse
sudo apt update
sudo apt install -y fuse3
omni up
```

**Comment by mahogl** [comment]
Just to add, i also did experienced this bug before i switched to the NFS config. 

Did a fresh install and could not get the mount the to work on the fresh install. So did a restore of my old server, with working mount and used that instead of the fresh install since i could not work out why it did not work.

**Comment by robnester** [comment]
> @meharrington90 Can you try the following on your host?
> 
> ```
> omni down
> sudo apt remove fuse
> sudo apt update
> sudo apt install -y fuse3
> omni up
> ```

I tried this, with no success. I'll await results from @meharrington90 to see if they're similar.

**Comment by kelinger** [comment]
Interesting because after I upgraded my fuse on the host, this eliminated the problem.

@robnester can you verify on the host that fuse3 is running?  `fusermount --v` (note there are two dashes)

You may also try rebooting to make sure the previous version was properly unloaded (I didn't need to reboot but fuse wasn't in use when I upgraded it, either)

**Comment by kelinger** [comment]
Well, please note that I have not rolled out that change to the setup process so its still going to install the older version.  However, on my pristine system, that didn't matter (once I upgraded it after the setup).

**Comment by meharrington90** [comment]
@kelinger @robnester Nogo on installing fuse3 either. Did a full omni clean, reboot, and still only listing the cloud folder.

**Comment by kelinger** [comment]
@robnester - Can you try `omni update` and see if it works now?

Anyone else:  please update fuse before trying this (see earlier discussion)

**Comment by robnester** [comment]
> @meharrington90 @robnester - Can you try `omni update` and see if it works now?
> 
> 
> 
> Anyone else:  please update fuse before trying this (see earlier discussion)

That works. I'd love to know what fixed it?

**Comment by meharrington90** [comment]
Nope, still nogo on the other folders. I wonder if using an older distro would be ideal. @robnester, what version of debian are you using?

**Comment by meharrington90** [comment]
Seems I am using Ubuntu 22.04.3 with FUSE 3.10. I'm going to attempt a Debian reinstall.

**Comment by meharrington90** [comment]
IT WORKED!! I gotta run the full restore, but the system is back online with a Debian reinstall and manually installing fuse3. Good work @kelinger!!!

I'd say the only thing that needs fixed next is the install script, changing fuse to fuse3.

**Comment by kelinger** [comment]
Right; I've already updated the installer but didn't want to push that out until we knew it, you know, worked 😄 !

I'm also going to put an updater in there so everyone else (assuming there's at least one person not in this thread who uses OmniStream) can get the Fuse upgrade.

**Comment by kelinger** [comment]
Updated installer with fuse3 as well as new upgrade process added.  System will now check for upgrades (takes milliseconds unless critical component, like fuse, needs a forced upgrade) upon `omni up` and `omni update` processes.

@Misterobots - this was your post so let us know if you're working now.  Feel free to reopen if not.

**Comment by Misterobots** [comment]
Wanted to comment on this and say THANK YOU! This set of steps resolved my issue. Thank you everyone for the team work and dedication.
