### ISSUE TITLE
Downloads Symbolic Link

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#8]
Is there a check on the Downloads symbolic link? The one for my home directory is still pointing to /mnt/uploads from my old Gooby install. I can delete it and re-link it into the uploadscache directory where it should go but I though I would ask. It may just be me and a remnant that were not removed when I removed Gooby. Let me know.

**Comment by TechPerplexed** [comment]
Ah yes it's just a remnant from Gooby and doesn't need to be there. In fact I thought the upgrade script would remove it... I'll double check that.

How is the upgrade treating you?

**Comment by shadowsbane0** [comment]
To be honest I’ve been working on other things while I wait for my media to transfer and I can rebuild the OS to try and fix the permission problems. At least then I won’t be troubleshooting issues with the OS and not OmniStream.

Sent from my iPad

On Mar 18, 2022, at 10:16, Tech Perplexed ***@***.***> wrote:

﻿

Ah yes it's just a remnant from Gooby and doesn't need to be there. In fact I thought the upgrade script would remove it... I'll double check that.

How is the upgrade treating you?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkelinger%2FOmniStream%2Fissues%2F8%23issuecomment-1072453717&data=04%7C01%7C%7C0c9f4a7d82054ff1a7d308da08e9de3c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832097791441204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iFTi1zjJL01HVztEInKoWrgxWTt8JszmGEcoX4kToP8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGFOA44ZZH6K5PSUZFTVASF3BANCNFSM5RB4HF3Q&data=04%7C01%7C%7C0c9f4a7d82054ff1a7d308da08e9de3c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832097791441204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=atpUair%2Bm%2FIheP6xt0i9ByL6aIn3wux3HRZa2PhHu6s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C0c9f4a7d82054ff1a7d308da08e9de3c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832097791441204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f%2FyvHF%2BoDQYRvNclEL4bybNYHbD0ztS2kPHAVKY4CVM%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C0c9f4a7d82054ff1a7d308da08e9de3c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832097791441204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0DaALDJN9MMBEOPngd5fmFOyAbCQuoWylIfox7d4aDE%3D&reserved=0>.

**Comment by TechPerplexed** [comment]
Haha fair enough... these things are meant to "set and forget" so I consider no news, good news in that regard :-D I'll close this issue now and will look into the upgrade script. Thanks for the heads up :)
